//! SpanZIP FFI — C ABI layer.
//!
//! Full contract: `docs/03-api/ffi-api.md`.
//! `spanzip.h` is auto-generated by `cbindgen` in `build.rs`.

#![warn(
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
)]
#![allow(
    clippy::missing_safety_doc,
    clippy::module_name_repetitions,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
)]

pub mod archive;
pub mod create;
pub mod error;
pub mod extract;
pub mod iterator;
pub mod reader;
pub mod test;
mod util;

pub use archive::{
    spanzip_archive_close, spanzip_archive_entry_count, spanzip_archive_format,
    spanzip_archive_is_encrypted, spanzip_archive_is_solid, spanzip_archive_open,
    spanzip_detect_format, spanzip_detect_format_bytes, SpanzipArchive,
};
pub use create::{
    spanzip_archive_add_directory, spanzip_archive_add_file, spanzip_archive_commit,
    spanzip_archive_create, spanzip_archive_rollback, SpanzipCreateOptions,
};
pub use error::ErrorCode;
pub use extract::{
    spanzip_archive_extract_all, SpanzipExtractOptions, SpanzipExtractReport, SpanzipProgressCb,
    SpanzipProgressView, SpanzipTestReport,
};
pub use iterator::{
    spanzip_iterator_free, spanzip_iterator_new, spanzip_iterator_next, SpanzipEntryView,
    SpanzipIterator,
};
pub use reader::{
    spanzip_reader_close, spanzip_reader_open, spanzip_reader_read, SpanzipReader,
};
pub use test::{spanzip_archive_test, spanzip_archive_test_corrupted_entry};

use std::os::raw::c_char;

/// ABI version — must increase on any breaking change in exported symbols.
/// See `ffi-api.md` §13 and `docs/CHANGELOG-ffi.md`.
///
/// v6 (2026-04-30, Phase 6+): `SpanzipCreateOptions` trailing append
/// `exclude_system_metadata: u8`. Backwards-compatible with v5 callers
/// (uninitialised tail reads as 0 = "include everything", matching the
/// previous unconditional behavior).
const ABI_VERSION: u32 = 6;

/// Returns a pointer to a null-terminated static version string.
///
/// # Safety
/// Returned pointer has `'static` lifetime. Do not free.
#[no_mangle]
pub extern "C" fn spanzip_version() -> *const c_char {
    static VERSION: &[u8] = concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes();
    VERSION.as_ptr().cast()
}

#[no_mangle]
pub extern "C" fn spanzip_abi_version() -> u32 {
    ABI_VERSION
}

/// Initialise the library. Idempotent. Returns 0 on success.
#[no_mangle]
pub extern "C" fn spanzip_init() -> i32 {
    // TODO(track-f): tracing_subscriber init (guarded by Once), rayon pool config
    0
}

#[no_mangle]
pub extern "C" fn spanzip_shutdown() {
    // TODO(track-f): graceful shutdown hooks
}
