//! RAR backend integration tests — `docs/05-build/rar-backend-plan.md` §4.
//!
//! RAR is **extraction only** (RARLAB's UnRAR licence forbids using the source
//! to build a RAR-compatible archiver), so unlike every other backend we cannot
//! author a fixture with our own writer. Fixtures come from two places:
//!
//! 1. `tests/fixtures/rar/*.rar` copied verbatim out of the `unrar` crate's own
//!    `data/` directory — real RARLAB-produced archives, including the RAR3
//!    entry-encrypted and RAR5 header-encrypted cases.
//! 2. `traversal.rar` / `backslash.rar` / `absolute.rar` / `symlink.rar`,
//!    generated by `tools/make-rar-fixtures.py`, which patches `version.rar`'s
//!    entry header in place and recomputes the RAR3 header CRC. Real unrar reads
//!    them back, which is the point: unrar's own parser is the judge of whether
//!    the hostile names we claim to defend against are actually reachable.
//!
//! The three things worth knowing before touching these tests:
//!
//! * **A wrong password on RAR3 is byte-identical to corruption.** unrar returns
//!   `BadData@Process` ("File CRC error") for both, because RAR3 has no password
//!   verifier. `map_unrar` therefore uses a heuristic guarded on *we supplied a
//!   password* AND *this entry is encrypted*. [`rar3_wrong_password_is_not_corrupted`]
//!   is the test that pins it; if it ever regresses to `Corrupted`, a user with a
//!   typo gets told their archive is destroyed.
//! * **Hostile filenames arrive verbatim.** `..\..\a` survives unrar's own
//!   cleaning ([`traversal_entry_blocked`]), so our guard is the only defence,
//!   not belt-and-braces.
//! * **Nothing here may create a RAR.** [`writer_still_refuses_rar`] is a licence
//!   guard, not a scope guard.

use std::path::{Path, PathBuf};

use otterzip_core::archive::ExtractWarning;
use otterzip_core::{
    Archive, ArchiveFormat, CreateOptions, ExtractOptions, OpenMode, OtterzipError,
    OverwritePolicy, Progress,
};
use tempfile::tempdir;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn fx(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("rar")
        .join(name)
}

fn open(name: &str) -> Archive {
    Archive::open(fx(name), OpenMode::Read).unwrap_or_else(|e| panic!("open {name}: {e:?}"))
}

fn open_pw(name: &str, pw: &str) -> otterzip_core::Result<Archive> {
    Archive::open_with_password(fx(name), OpenMode::Read, pw.to_owned())
}

fn extract_opts(dest: &Path) -> ExtractOptions {
    ExtractOptions {
        destination: dest.to_path_buf(),
        overwrite: OverwritePolicy::Always,
        ..Default::default()
    }
}

fn extract(ar: &Archive, dest: &Path) -> otterzip_core::Result<otterzip_core::ExtractReport> {
    ar.extract_all::<fn(&Progress) -> bool>(&extract_opts(dest), None)
}

fn entry_paths(ar: &Archive) -> Vec<String> {
    ar.entries()
        .unwrap()
        .map(|e| e.unwrap().path)
        .collect::<Vec<_>>()
}

/// Every regular file under `root`, as paths relative to it.
fn walk(root: &Path) -> Vec<PathBuf> {
    fn go(dir: &Path, root: &Path, out: &mut Vec<PathBuf>) {
        let Ok(rd) = std::fs::read_dir(dir) else {
            return;
        };
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                go(&p, root, out);
            } else if let Ok(rel) = p.strip_prefix(root) {
                out.push(rel.to_path_buf());
            }
        }
    }
    let mut out = Vec::new();
    go(root, root, &mut out);
    out.sort();
    out
}

/// The scratch dirs `Scratch::new_in` creates inside `dest_root`. Every one of
/// these that survives a call is a leak — `Scratch`'s `Drop` is what keeps a
/// failed extract from littering the user's output folder with half-written
/// files, which for a multi-volume-first format is the *common* path, not a
/// corner case.
fn scratch_dirs(dest_root: &Path) -> Vec<String> {
    let Ok(rd) = std::fs::read_dir(dest_root) else {
        return Vec::new();
    };
    rd.flatten()
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with(".otterzip-rar-"))
        .collect()
}

// ---------------------------------------------------------------------------
// plain RAR3
// ---------------------------------------------------------------------------

#[test]
fn plain_rar3_lists_entries() {
    let ar = open("version.rar");
    let entries = ar.entries().unwrap().collect::<Result<Vec<_>, _>>().unwrap();
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].path, "VERSION");
    assert!(!entries[0].is_directory);
    assert!(!entries[0].is_symlink);
    assert_eq!(entries[0].uncompressed_size, 11);
    assert_eq!(
        entries[0].encryption,
        otterzip_core::format::EncryptionMethod::None
    );
}

#[test]
fn plain_rar3_detects_as_rar() {
    assert_eq!(otterzip_core::detect(fx("version.rar")).unwrap(), ArchiveFormat::Rar);
}

#[test]
fn plain_rar3_extracts() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("version.rar");
    let report = extract(&ar, &out).unwrap();

    assert_eq!(report.entries_extracted, 1);
    assert_eq!(report.bytes_written, 11);
    assert_eq!(std::fs::read(out.join("VERSION")).unwrap(), b"unrar-0.4.0");
    assert!(scratch_dirs(&out).is_empty(), "scratch leaked on the success path");
}

#[test]
fn solid_archive_extracts() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("solid.rar");
    let report = extract(&ar, &out).unwrap();

    assert_eq!(report.entries_extracted, 1);
    assert_eq!(
        std::fs::read(out.join(".gitignore")).unwrap(),
        b"target\nCargo.lock\n"
    );
}

#[test]
fn unicode_names_roundtrip() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("unicode.rar");

    // unrar hands names back as UTF-16; `rar_path` lossy-converts and swaps `\`
    // for `/`. Neither step may mangle a name that has no backslash in it.
    assert_eq!(entry_paths(&ar), vec!["te…―st✌"]);
    extract(&ar, &out).unwrap();
    assert_eq!(
        std::fs::read(out.join("te…―st✌")).unwrap(),
        "🆃🄴🆂🅃\n".as_bytes()
    );
}

// ---------------------------------------------------------------------------
// passwords — RAR3 (entry-encrypted, plaintext names)
// ---------------------------------------------------------------------------

#[test]
fn rar3_entry_encrypted_is_encrypted_without_password() {
    // `rar a -p` leaves filenames in plaintext, so listing works with no
    // password and the per-entry flag is readable. This is what lights up the
    // C# password dialog for an entry-encrypted RAR — it MUST NOT error.
    let ar = open("crypted.rar");
    assert!(ar.is_encrypted().unwrap());
    assert_eq!(entry_paths(&ar), vec![".gitignore"]);
}

#[test]
fn rar3_encrypted_correct_password() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open_pw("crypted.rar", "unrar").unwrap();
    let report = extract(&ar, &out).unwrap();

    assert_eq!(report.entries_extracted, 1);
    assert_eq!(
        std::fs::read(out.join(".gitignore")).unwrap(),
        b"target\nCargo.lock\n"
    );
}

#[test]
fn rar3_no_password_is_wrong_password() {
    // MissingPassword@Process. Must be WrongPassword, not a generic backend
    // error, or the password dialog never appears.
    let td = tempdir().unwrap();
    let ar = open("crypted.rar");
    let err = extract(&ar, &td.path().join("out")).unwrap_err();
    assert!(matches!(err, OtterzipError::WrongPassword), "got {err:?}");
}

#[test]
fn rar3_wrong_password_is_not_corrupted() {
    // ** THE ONE. **
    //
    // RAR3 has no password verifier: unrar decrypts to garbage, the CRC fails,
    // and the DLL returns `BadData@Process` — the SAME code as genuine
    // corruption, with the same "File CRC error" text. unrar's own UI can tell
    // them apart (extract.cpp:910-926 picks UIERROR_CHECKSUMENC over
    // UIERROR_CHECKSUM) but the DLL does not export the distinction, so
    // `map_unrar` guesses, guarded on `password supplied && entry encrypted`.
    //
    // It guesses in the recoverable direction on purpose. If this ever
    // regresses to `Corrupted`, a user who fat-fingered their password is told
    // their archive is destroyed — and there is no way for them to find out
    // otherwise.
    let td = tempdir().unwrap();
    let ar = open_pw("crypted.rar", "WRONG-PASSWORD").unwrap();
    let err = extract(&ar, &td.path().join("out")).unwrap_err();

    assert!(
        matches!(err, OtterzipError::WrongPassword),
        "wrong password on RAR3 must map to WrongPassword, got {err:?}"
    );
    assert!(
        !matches!(err, OtterzipError::Corrupted { .. }),
        "regression: the BadData heuristic stopped firing"
    );
}

#[test]
fn unencrypted_rar_is_not_encrypted() {
    // The negative half of the heuristic's guard: `entry.encrypted` is what
    // stops a genuinely corrupt *plain* entry being reported as a password
    // problem. If this ever returns true the guard is meaningless.
    assert!(!open("version.rar").is_encrypted().unwrap());
    assert!(!open("solid.rar").is_encrypted().unwrap());
}

// ---------------------------------------------------------------------------
// passwords — RAR5 -hp (header-encrypted)
// ---------------------------------------------------------------------------

#[test]
fn rar5_hp_no_password_is_wrong_password() {
    // `open_for_listing()` returns Ok even with no password (RAROpenArchiveEx
    // runs before RARSetPassword), so `RarBackend::open` forces a metadata pass
    // to make the failure land at open — matching 7z, and giving the C# layer
    // the WrongPassword it catches to raise the dialog.
    let err = Archive::open(fx("comment-hpw-password.rar"), OpenMode::Read).unwrap_err();
    assert!(matches!(err, OtterzipError::WrongPassword), "got {err:?}");
}

#[test]
fn rar5_hp_wrong_password_is_wrong_password() {
    // BadPassword@Read. Unlike RAR3, RAR5 -hp *does* tell us — no heuristic.
    let err = open_pw("comment-hpw-password.rar", "WRONG-PASSWORD").unwrap_err();
    assert!(matches!(err, OtterzipError::WrongPassword), "got {err:?}");
}

#[test]
fn rar5_hp_correct_password_extracts() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open_pw("comment-hpw-password.rar", "password").unwrap();

    // `is_encrypted_fast` must be the O(1) ROADF_ENCHEADERS answer, not a walk.
    assert!(ar.is_encrypted().unwrap());
    let report = extract(&ar, &out).unwrap();
    assert_eq!(report.entries_extracted, 1);
    assert_eq!(
        std::fs::read(out.join(".gitignore")).unwrap(),
        b"target\nCargo.lock\n"
    );
}

// ---------------------------------------------------------------------------
// password encoding — the CP_ACP fix (plan §3.1)
// ---------------------------------------------------------------------------

#[test]
fn nul_in_password_is_invalid_argument() {
    // The crate does `CString::new(pw).unwrap()` (open_archive.rs:243), which
    // PANICS on an interior NUL. Screened before the crate ever sees it.
    let err = open_pw("crypted.rar", "ab\0cd").unwrap_err();
    assert!(
        matches!(err, OtterzipError::InvalidArgument(_)),
        "got {err:?}"
    );
}

#[test]
fn long_password_truncates_not_errors() {
    // Regression guard. crypt.cpp:57 truncates at MAXPASSWORD-1 "For
    // compatibility with existing archives", and WinRAR does the same — so a
    // long password must be *tried and rejected*, never refused up front.
    // Refusing would mean declining archives that open fine everywhere else.
    let long = "x".repeat(200);
    // Either open refuses it (the regression we are guarding against) or it gets
    // as far as being tried and found wrong (correct). Collapse both to the one
    // error we then judge.
    let err = open_pw("crypted.rar", &long)
        .map(|ar| {
            let td = tempdir().unwrap();
            extract(&ar, &td.path().join("out"))
                .expect_err("a 200-char password is still the wrong password")
        })
        .unwrap_or_else(|e| e);

    assert!(
        matches!(err, OtterzipError::WrongPassword),
        "a long password must be truncated and tried, not rejected: {err:?}"
    );
    assert!(
        !matches!(err, OtterzipError::InvalidArgument(_)),
        "regression: a length gate was added; WinRAR accepts these"
    );
}

#[test]
fn non_ascii_password_is_never_silently_mangled() {
    // `RARSetPassword` is the ANSI entry point: unrar runs
    // MultiByteToWideChar(CP_ACP, ..) (unicode.cpp:90) on whatever bytes it is
    // handed, while the crate hands it raw UTF-8. On CP949/932/936 that
    // silently turns a correct non-ASCII password into a different one —
    // "wrong password" on archives WinRAR opens fine. `password_bytes_for_unrar`
    // pre-encodes to the ACP so unrar's decode round-trips.
    //
    // WHAT THIS CAN AND CANNOT PROVE: proving the round trip *succeeds* needs a
    // RAR authored with a non-ASCII password, which needs RARLAB's `rar` (plan
    // §4.2 flags this P0 gap). What it does pin is that both branches are
    // *reachable and typed*: either the ACP encodes the password and unrar
    // rejects it as wrong (CP949 here), or the ACP cannot represent it and we
    // fail LOUDLY. What must never happen is a mangled password reaching unrar
    // as `Corrupted`/`BackendError`, or a panic.
    let outcome = open_pw("crypted.rar", "암호")
        .map(|ar| {
            let td = tempdir().unwrap();
            extract(&ar, &td.path().join("out")).expect_err("암호 is not the password")
        })
        .unwrap_or_else(|e| e);

    match outcome {
        // ACP encoded it (e.g. CP949): the conversion ran, unrar decoded it back
        // and simply says no.
        OtterzipError::WrongPassword => {}
        // ACP cannot represent it (e.g. CP1252): the `used_default` probe fired.
        // Loud is the whole point — silently sending "??" would report a wrong
        // password for a correct one.
        OtterzipError::InvalidArgument(_) => {}
        other => panic!("non-ASCII password produced an untyped failure: {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// multi-volume
// ---------------------------------------------------------------------------

#[test]
fn missing_volume_errors_not_truncates() {
    // `archive.part1.rar` ships deliberately incomplete. The List iterator
    // latches `damaged = true` on the first Err and then returns None FOREVER
    // (open_archive.rs:294-315), so a `.filter_map(Result::ok)` here would turn
    // "part 2 is missing" into "a smaller archive" with no error at all: the
    // user extracts a prefix of their files and is told it worked.
    let ar = open("archive.part1.rar");
    let err = ar.entries().err().expect("listing an incomplete set must fail");
    match err {
        OtterzipError::MissingVolume { expected_name, .. } => {
            assert_eq!(expected_name.as_deref(), Some("archive.part2.rar"));
        }
        other => panic!("expected MissingVolume, got {other:?}"),
    }
}

#[test]
fn missing_volume_extract_errors_and_leaves_no_scratch() {
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("archive.part1.rar");
    let err = extract(&ar, &out).unwrap_err();

    assert!(matches!(err, OtterzipError::MissingVolume { .. }), "got {err:?}");
    assert!(walk(&out).is_empty(), "a failed set must publish nothing");
    assert!(scratch_dirs(&out).is_empty(), "scratch leaked: {:?}", scratch_dirs(&out));
}

#[test]
fn non_first_volume_redirects_to_first_part() {
    // Right-clicking `foo.part03.rar` must extract the whole set, so
    // `RarBackend::open` applies `first_part()` once at open.
    //
    // Proven by redirection rather than by inspecting a path: part 1 and part 2
    // are DIFFERENT archives with different entry names, and we open part 2. If
    // the redirect is live we see part 1's entry; if it silently regressed we
    // would see part 2's own, and the test could not be fooled by a `first_part`
    // that returned its input unchanged.
    let td = tempdir().unwrap();
    let p1 = td.path().join("redirect.part00001.rar");
    let p2 = td.path().join("redirect.part00002.rar");
    std::fs::copy(fx("version.rar"), &p1).unwrap(); // entry: VERSION
    std::fs::copy(fx("solid.rar"), &p2).unwrap(); // entry: .gitignore

    let ar = Archive::open(&p2, OpenMode::Read).unwrap();
    assert_eq!(
        entry_paths(&ar),
        vec!["VERSION"],
        "opening part 2 must read part 1"
    );

    let out = td.path().join("out");
    extract(&ar, &out).unwrap();
    assert_eq!(std::fs::read(out.join("VERSION")).unwrap(), b"unrar-0.4.0");
}

#[test]
fn non_first_volume_without_its_first_part_errors() {
    // `100M.part00002.rar` ships without a part 1, so the redirect lands on a
    // file that does not exist -> EOpen@Open.
    //
    // DOCUMENTS A KNOWN ROUGH EDGE, it does not bless it: per plan §3.2
    // `(EOpen, _)` maps to Io(NotFound), so the user is told "could not open RAR
    // archive" when the truthful answer is MissingVolume { expected:
    // 100M.part00001.rar } — arguably the single most common real RAR mistake.
    // Left faithful to the plan; if that mapping is revisited, this assertion is
    // the one to change, and changing it is an improvement.
    let err = Archive::open(fx("100M.part00002.rar"), OpenMode::Read).unwrap_err();
    match err {
        OtterzipError::Io(e) => assert_eq!(e.kind(), std::io::ErrorKind::NotFound),
        other => panic!("expected Io(NotFound), got {other:?}"),
    }
}

// ---------------------------------------------------------------------------
// hostile names — generated fixtures (tools/make-rar-fixtures.py)
// ---------------------------------------------------------------------------

#[test]
fn traversal_entry_blocked() {
    // The entry is named `..\..\a` and unrar hands it back VERBATIM — its own
    // cleaning does not strip `..`. So this is the only thing between the
    // archive and the filesystem, not a second line of defence.
    //
    // dest_root is nested two deep so the escape has somewhere real to land:
    // `<td>/deep/out/../../a` resolves to `<td>/a`.
    let td = tempdir().unwrap();
    let out = td.path().join("deep").join("out");
    let ar = open("traversal.rar");

    assert_eq!(entry_paths(&ar), vec!["../../a"], "normalised, not yet judged");

    let err = extract(&ar, &out).unwrap_err();
    match err {
        OtterzipError::PathTraversalBlocked(p) => assert_eq!(p, "../../a"),
        other => panic!("expected PathTraversalBlocked, got {other:?}"),
    }
    assert!(!td.path().join("a").exists(), "escaped to <td>/a");
    assert!(!td.path().join("deep").join("a").exists(), "escaped to <td>/deep/a");
    assert!(
        walk(td.path()).is_empty(),
        "nothing may be written anywhere: {:?}",
        walk(td.path())
    );
    assert!(scratch_dirs(&out).is_empty(), "scratch leaked on the traversal path");
}

#[test]
fn backslash_names_normalize() {
    // RAR stores `\` on Windows-created archives. Normalising is CLAUDE.md rule
    // 3, but it is also required for correctness: `__validate_component` rejects
    // an embedded backslash, so an unnormalised `a\b\c.t` would be misreported
    // as *traversal* — a false positive on a perfectly ordinary archive.
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("backslash.rar");

    assert_eq!(entry_paths(&ar), vec!["a/b/c.t"]);

    let report = extract(&ar, &out).unwrap();
    assert_eq!(report.entries_extracted, 1);
    // Real nested directories, not one file with backslashes in its name.
    assert!(out.join("a").is_dir());
    assert!(out.join("a").join("b").is_dir());
    assert_eq!(
        std::fs::read(out.join("a").join("b").join("c.t")).unwrap(),
        b"unrar-0.4.0"
    );
}

#[test]
fn absolute_path_entry_is_contained() {
    // The entry is authored as `C:\ev.t`, but unrar rewrites the drive colon and
    // hands back `C_\ev.t`. Documents the boundary precisely: our colon check is
    // NOT what saves us from absolute paths here — unrar got there first — so
    // the `..` rejection in `traversal_entry_blocked` is carrying the load. If
    // unrar ever stops sanitising, this test flips to a containment failure and
    // tells us.
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("absolute.rar");

    assert_eq!(entry_paths(&ar), vec!["C_/ev.t"]);
    extract(&ar, &out).unwrap();

    assert!(out.join("C_").join("ev.t").exists());
    assert!(
        walk(&out).iter().all(|p| out.join(p).starts_with(&out)),
        "entry escaped dest_root"
    );
}

#[test]
fn symlink_entry_skipped_and_contained() {
    // `symlink.rar` is `version.rar` with ATTR patched to 0xa1ff (S_IFLNK|0777)
    // — the exact bits unrar itself derives FSREDIR_UNIXSYMLINK from
    // (arcread.cpp:307-309).
    //
    // Matters because `extract_to` sets CurConvertSymlinkPaths=false, turning
    // OFF unrar's own symlink-escape defence, while still creating REAL reparse
    // points. We can neither ask unrar to skip links nor see redir_type through
    // the wrapper — so the entry must be skipped, and its "contents" (the link
    // target) must never be written as a file.
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("symlink.rar");

    let entries = ar.entries().unwrap().collect::<Result<Vec<_>, _>>().unwrap();
    assert!(entries[0].is_symlink, "fixture must present as a link record");

    let report = extract(&ar, &out).unwrap();
    assert_eq!(report.entries_extracted, 0, "a link record must not be extracted");
    assert_eq!(report.entries_skipped, 1);
    assert!(
        report
            .warnings
            .iter()
            .any(|w| matches!(w, ExtractWarning::SymlinkSkipped { .. })),
        "skipping must be reported, not silent: {:?}",
        report.warnings
    );
    assert!(!out.join("VERSION").exists(), "link target written as a file");
    assert!(walk(&out).is_empty(), "nothing may be published: {:?}", walk(&out));
    assert!(scratch_dirs(&out).is_empty());
}

#[test]
fn symlink_entry_body_is_never_streamed() {
    // The `read_entry` / `Archive::test` route has no `harvest` to fall back on
    // (RAR_TEST creates no file), so it carries its own refusal. Without it a
    // link entry would hand its TARGET PATH back as the entry's "contents".
    let ar = open("symlink.rar");
    let err = ar.read_entry("VERSION").err().expect("must refuse a link record");
    assert!(matches!(err, OtterzipError::Corrupted { .. }), "got {err:?}");
}

// ---------------------------------------------------------------------------
// declared size is a lie, and it is the attacker's lie
// ---------------------------------------------------------------------------

#[test]
fn inflated_declared_size_does_not_become_a_resource_cost() {
    // `bigdecl.rar` declares UNP_SIZE = 100 MiB over 11 real bytes.
    //
    // `extract_entry` used to branch on that number: above 64 MiB it staged the
    // entry through `extract_to` into %TEMP% and let unrar `Prealloc(UnpSize)`
    // claim the DECLARED size up front (extract.cpp:773-780) — so a header field
    // the archive chose decided how much of C: to consume, on `Archive::test`,
    // the one API a user runs precisely because they distrust the archive. None
    // of `extract_all_inner`'s gates covered it: RAR overrides
    // `extract_all_streaming`, so `Archive::test` and `read_entry` never meet
    // them.
    //
    // Now every size goes through `read()` (RAR_TEST), which creates no file and
    // preallocates nothing, and whose `Vec` grows with the REAL data. The unit
    // test `extract_entry_never_stages_through_temp` pins the %TEMP% half; this
    // pins the contract a caller sees: the lie yields 11 bytes, not 100 MiB.
    let ar = open("bigdecl.rar");
    let entries = ar.entries().unwrap().collect::<Result<Vec<_>, _>>().unwrap();
    assert_eq!(
        entries[0].uncompressed_size,
        100 * 1024 * 1024,
        "fixture must declare 100 MiB or it proves nothing"
    );

    let mut buf = Vec::new();
    std::io::Read::read_to_end(&mut ar.read_entry("VERSION").unwrap(), &mut buf).unwrap();
    assert_eq!(buf, b"unrar-0.4.0", "only the real bytes may be produced");

    // And `Archive::test` — the caller that has no cap of its own — agrees.
    let report = ar.test::<fn(&Progress) -> bool>(None).unwrap();
    assert_eq!(report.entries_tested, 1);
}

// ---------------------------------------------------------------------------
// scratch lifetime
// ---------------------------------------------------------------------------

#[test]
fn scratch_is_cleaned_on_cancel() {
    // The scratch is created before the loop, so it is live when the first
    // progress callback runs. Cancelling there must leave dest_root pristine —
    // `Scratch`'s Drop is what makes "cancel" mean "nothing happened" rather
    // than "half a file with a real name".
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let mut cancel = |_: &Progress| false;
    let ar = open("version.rar");

    let err = ar
        .extract_all(&extract_opts(&out), Some(&mut cancel))
        .unwrap_err();

    assert!(matches!(err, OtterzipError::Canceled), "got {err:?}");
    assert!(scratch_dirs(&out).is_empty(), "scratch leaked: {:?}", scratch_dirs(&out));
    assert!(walk(&out).is_empty(), "cancel published files: {:?}", walk(&out));
}

#[test]
fn scratch_is_cleaned_on_mid_extract_error() {
    // traversal.rar fails AFTER the scratch exists (the missing-volume case
    // fails during the metadata pass, before it is created), so this is the case
    // that actually exercises Drop on the error path.
    let td = tempdir().unwrap();
    let out = td.path().join("out");
    let ar = open("traversal.rar");

    assert!(extract(&ar, &out).is_err());
    assert!(scratch_dirs(&out).is_empty(), "scratch leaked: {:?}", scratch_dirs(&out));
}

// ---------------------------------------------------------------------------
// licence guard
// ---------------------------------------------------------------------------

#[test]
fn writer_still_refuses_rar() {
    // NOT a scope guard. The RARLAB UnRAR licence forbids using the source to
    // develop a RAR-compatible archiver, so `writer.rs`'s `F::Rar =>
    // FeatureDisabled` is a LEGAL constraint. Reading RAR does not relax it.
    // Duplicated from sprint4_writer.rs on purpose: it must fail here too, next
    // to the code that made reading possible.
    let td = tempdir().unwrap();
    let opts = CreateOptions {
        format: ArchiveFormat::Rar,
        ..Default::default()
    };
    let err = Archive::create(td.path().join("nope.rar"), opts).unwrap_err();
    assert!(matches!(err, OtterzipError::FeatureDisabled(_)), "got {err:?}");
}

#[test]
fn rar_update_mode_refused() {
    // The other half of extract-only: no in-place modification either.
    let err = Archive::open(fx("version.rar"), OpenMode::Update).unwrap_err();
    assert!(matches!(err, OtterzipError::FeatureDisabled(_)), "got {err:?}");
}
