//! OtterZip FFI — C ABI layer.
//!
//! Full contract: `docs/03-api/ffi-api.md`.
//! `otterzip.h` is auto-generated by `cbindgen` in `build.rs`.

#![warn(
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
)]
#![allow(
    clippy::missing_safety_doc,
    clippy::module_name_repetitions,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
)]

pub mod archive;
pub mod create;
pub mod error;
pub mod extract;
pub mod iterator;
pub mod reader;
pub mod test;
mod util;

pub use archive::{
    otterzip_archive_close, otterzip_archive_entry_count, otterzip_archive_format,
    otterzip_archive_is_encrypted, otterzip_archive_is_solid, otterzip_archive_open,
    otterzip_detect_format, otterzip_detect_format_bytes, OtterzipArchive,
};
pub use create::{
    otterzip_archive_add_directory, otterzip_archive_add_directory_p, otterzip_archive_add_file,
    otterzip_archive_commit, otterzip_archive_create, otterzip_archive_rollback,
    OtterzipCreateOptions,
};
pub use error::ErrorCode;
pub use extract::{
    otterzip_archive_extract_all, OtterzipExtractOptions, OtterzipExtractReport, OtterzipProgressCb,
    OtterzipProgressView, OtterzipTestReport,
};
pub use iterator::{
    otterzip_iterator_free, otterzip_iterator_new, otterzip_iterator_next, OtterzipEntryView,
    OtterzipIterator,
};
pub use reader::{
    otterzip_reader_close, otterzip_reader_open, otterzip_reader_read, OtterzipReader,
};
pub use test::{otterzip_archive_test, otterzip_archive_test_corrupted_entry};

use std::os::raw::c_char;

/// ABI version — must increase on any breaking change in exported symbols.
/// See `ffi-api.md` §13 and `docs/CHANGELOG-ffi.md`.
///
/// v6 (2026-04-30, Phase 6+): `OtterzipCreateOptions` trailing append
/// `exclude_system_metadata: u8`. Backwards-compatible with v5 callers
/// (uninitialised tail reads as 0 = "include everything", matching the
/// previous unconditional behavior).
///
/// v7 (2026-05-12, Phase 6+): adds `otterzip_archive_add_directory_p` —
/// progress + cancel-aware variant of `_add_directory`. The original
/// no-callback symbol is preserved unchanged.
///
/// v8 (2026-05-13): adds `otterzip_archive_open_multi` — opens a split
/// / spanned ZIP given an explicit ordered list of volume paths. Backed
/// by `Archive::open_multi` and the new `MultiVolumeReader` virtual
/// stream. Single-volume read path is unchanged.
///
/// v9 (2026-05-14): `OtterzipProgressView` trailing append
/// `current_entry_bytes_processed` + `current_entry_bytes_total`
/// (both `u64`). Fills with the per-file streaming progress the
/// compress sprint's `add_entry_streaming` path emits ~1× per MiB.
/// v8 consumers that read only the leading fields stay binary-
/// compatible — the additional bytes are zero on every non-streaming
/// tick and ignored by callers that don't look for them.
const ABI_VERSION: u32 = 9;

/// Returns a pointer to a null-terminated static version string.
///
/// # Safety
/// Returned pointer has `'static` lifetime. Do not free.
#[no_mangle]
pub extern "C" fn otterzip_version() -> *const c_char {
    static VERSION: &[u8] = concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes();
    VERSION.as_ptr().cast()
}

#[no_mangle]
pub extern "C" fn otterzip_abi_version() -> u32 {
    ABI_VERSION
}

/// Initialise the library. Idempotent. Returns 0 on success.
///
/// Side effect (Phase perf-diag, 2026-05-13): installs a global
/// `tracing` subscriber writing to `%TEMP%\otterzip\otterzip.log`
/// on Windows (and `/tmp/otterzip/otterzip.log` elsewhere). Filter
/// honours the `OTTERZIP_LOG` env var when set, defaults to
/// `info,otterzip_core=debug,otterzip_ffi=debug`. The guard is
/// leaked so the file appender keeps flushing for the entire process
/// lifetime — `otterzip_shutdown` already gets called only on
/// graceful exit and we'd rather lose 64 bytes of WorkerGuard than
/// truncate the last buffer.
#[no_mangle]
pub extern "C" fn otterzip_init() -> i32 {
    static INIT: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    INIT.get_or_init(|| {
        if let Err(e) = install_subscriber() {
            // No subscriber yet; eprintln is the only signal channel.
            eprintln!("otterzip: tracing subscriber install failed: {e}");
        }
    });
    0
}

fn install_subscriber() -> std::io::Result<()> {
    use tracing_subscriber::{EnvFilter, fmt};
    let dir = log_dir();
    std::fs::create_dir_all(&dir)?;
    let file_appender = tracing_appender::rolling::never(&dir, "otterzip.log");
    let (non_blocking, guard) = tracing_appender::non_blocking(file_appender);
    // Leak the guard so flush keeps running for the whole process.
    std::mem::forget(guard);

    let filter = EnvFilter::try_from_env("OTTERZIP_LOG").unwrap_or_else(|_| {
        EnvFilter::new("info,otterzip_core=debug,otterzip_ffi=debug")
    });
    let subscriber = fmt::Subscriber::builder()
        .with_env_filter(filter)
        .with_writer(non_blocking)
        .with_ansi(false)
        .with_target(true)
        .with_thread_ids(true)
        .with_thread_names(true)
        .with_level(true)
        .with_file(false)
        .with_line_number(false)
        .finish();
    // Idempotent — if already set by tests, ignore.
    let _ = tracing::subscriber::set_global_default(subscriber);
    tracing::info!(
        version = env!("CARGO_PKG_VERSION"),
        abi = ABI_VERSION,
        dir = %dir.display(),
        "otterzip tracing subscriber installed"
    );
    Ok(())
}

fn log_dir() -> std::path::PathBuf {
    #[cfg(windows)]
    {
        if let Ok(temp) = std::env::var("TEMP") {
            return std::path::PathBuf::from(temp).join("otterzip");
        }
    }
    std::path::PathBuf::from("/tmp/otterzip")
}

#[no_mangle]
pub extern "C" fn otterzip_shutdown() {
    // TODO(track-f): graceful shutdown hooks
}
