//! OtterZip FFI — C ABI layer.
//!
//! Full contract: `docs/03-api/ffi-api.md`.
//! `otterzip.h` is auto-generated by `cbindgen` in `build.rs`.

#![warn(
    clippy::pedantic,
    clippy::undocumented_unsafe_blocks,
)]
#![allow(
    clippy::missing_safety_doc,
    clippy::module_name_repetitions,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
)]

pub mod archive;
pub mod create;
pub mod error;
pub mod extract;
pub mod iterator;
pub mod reader;
pub mod test;
mod util;

pub use archive::{
    otterzip_archive_close, otterzip_archive_entry_count, otterzip_archive_format,
    otterzip_archive_is_encrypted, otterzip_archive_is_solid, otterzip_archive_open,
    otterzip_detect_format, otterzip_detect_format_bytes, OtterzipArchive,
};
pub use create::{
    otterzip_archive_add_directory, otterzip_archive_add_file, otterzip_archive_commit,
    otterzip_archive_create, otterzip_archive_rollback, OtterzipCreateOptions,
};
pub use error::ErrorCode;
pub use extract::{
    otterzip_archive_extract_all, OtterzipExtractOptions, OtterzipExtractReport, OtterzipProgressCb,
    OtterzipProgressView, OtterzipTestReport,
};
pub use iterator::{
    otterzip_iterator_free, otterzip_iterator_new, otterzip_iterator_next, OtterzipEntryView,
    OtterzipIterator,
};
pub use reader::{
    otterzip_reader_close, otterzip_reader_open, otterzip_reader_read, OtterzipReader,
};
pub use test::{otterzip_archive_test, otterzip_archive_test_corrupted_entry};

use std::os::raw::c_char;

/// ABI version — must increase on any breaking change in exported symbols.
/// See `ffi-api.md` §13 and `docs/CHANGELOG-ffi.md`.
///
/// v6 (2026-04-30, Phase 6+): `OtterzipCreateOptions` trailing append
/// `exclude_system_metadata: u8`. Backwards-compatible with v5 callers
/// (uninitialised tail reads as 0 = "include everything", matching the
/// previous unconditional behavior).
const ABI_VERSION: u32 = 6;

/// Returns a pointer to a null-terminated static version string.
///
/// # Safety
/// Returned pointer has `'static` lifetime. Do not free.
#[no_mangle]
pub extern "C" fn otterzip_version() -> *const c_char {
    static VERSION: &[u8] = concat!(env!("CARGO_PKG_VERSION"), "\0").as_bytes();
    VERSION.as_ptr().cast()
}

#[no_mangle]
pub extern "C" fn otterzip_abi_version() -> u32 {
    ABI_VERSION
}

/// Initialise the library. Idempotent. Returns 0 on success.
#[no_mangle]
pub extern "C" fn otterzip_init() -> i32 {
    // TODO(track-f): tracing_subscriber init (guarded by Once), rayon pool config
    0
}

#[no_mangle]
pub extern "C" fn otterzip_shutdown() {
    // TODO(track-f): graceful shutdown hooks
}
